import { test, expect } from '@playwright/test';

test('mobile registration, schedule, sleep, comment, history and logout persist', async ({ page }) => {
    const dayBefore = (days) => new Intl.DateTimeFormat('sv-SE', { timeZone: 'Europe/Moscow' }).format(new Date(Date.now() - days * 86400000));
    const previousDay = dayBefore(3);
    const sleepDay = dayBefore(2);
    const email = `prototype-${Date.now()}@example.com`;
    const errors = [];
    page.on('pageerror', (error) => errors.push(error.message));
    await page.route('**/config.js', route=>route.fulfill({contentType:'application/javascript',body:'globalThis.__BABY_CONFIG__ = {registrationEnabled:true};'}));
    await page.goto('/register');
    await page.getByLabel('Ваше имя').fill('Тестовая мама');
    await page.getByLabel('Email', { exact: true }).fill(email);
    await page.getByLabel('Пароль', { exact: true }).fill('Prototype-test-123');
    await page.getByRole('button', { name: 'Создать аккаунт' }).click();
    await expect(page.getByRole('heading', { name: 'Новый день', exact: true })).toBeVisible();
    await page.getByRole('link', { name: 'Мои графики', exact: true }).click();
    await page.getByRole('button', { name: 'Создать график', exact: true }).click();
    await page.getByLabel('Название графика').fill('Обычный день');
    await page.getByLabel('Описание',{exact:true}).fill('Два сна и спокойный вечер');
    await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Обычный день', exact: true })).toBeVisible();
    await expect(page.getByText('Два сна и спокойный вечер',{exact:true})).toBeVisible();
    await page.getByRole('button', { name: 'Сделать по умолчанию', exact: true }).click();
    await expect(page.getByText('По умолчанию', { exact: true })).toBeVisible();
    await page.getByRole('link', { name: 'Сегодня', exact: true }).click();

    await page.getByRole('button', { name: 'Добавить ночной сон' }).click();
    await page.getByLabel('День цикла', { exact: true }).fill(previousDay);
    await page.getByLabel('Вид сна').selectOption('night');
    await page.getByLabel('Начало сна').fill(`${previousDay}T21:00`);
    await page.getByLabel('Конец сна (пусто — ещё спит)').fill(`${sleepDay}T06:30`);
    await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Записать сон' })).toHaveCount(0);
    await page.getByRole('button', { name: 'Выбрать дату' }).click();
    await page.getByRole('textbox', { name: 'День дневника', exact: true }).fill(sleepDay);
    await expect(page.locator('.previous-night-context')).toContainText('21:00 — 06:30');
    await page.getByRole('button', { name: 'Добавить прошедший сон' }).click();
    await page.getByLabel('Начало сна').fill(`${sleepDay}T10:50`);
    await page.getByLabel('Конец сна (пусто — ещё спит)').fill(`${sleepDay}T12:10`);
    await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
    await page.locator('.time-row.awake').first().getByRole('button', { name: 'Добавить заметку' }).click();
    await page.getByLabel('Заметка', { exact: true }).fill('Утро без спешки');
    await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
    await expect(page.getByText('Утро без спешки', { exact: true })).toBeVisible();
    await page.reload();
    await expect(page.getByText('Утро без спешки', { exact: true })).toBeVisible();
    await expect(page.getByText('1 ч 20 м').first()).toBeVisible();
    await page.screenshot({ path: 'test-results/mobile-day.png', fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
    await page.getByRole('link', { name: 'История', exact: true }).click();
    await expect(page.getByRole('link', { name: sleepDay, exact: true })).toBeVisible();
    await page.getByRole('link', { name: 'Профиль', exact: true }).click();
    await page.getByRole('button', { name: 'Выйти из аккаунта', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Рады видеть вас снова', exact: true })).toBeVisible();
    await page.getByLabel('Email', { exact: true }).fill(email);
    await page.getByLabel('Пароль', { exact: true }).fill('Prototype-test-123');
    await page.getByRole('button', { name: 'Войти', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Новый день', exact: true })).toBeVisible();
    expect(errors).toEqual([]);
});
