import { test, expect } from '@playwright/test';

test('night completion defines morning; editing its note persists on the source date', async ({ page }) => {
    const date = offset => new Intl.DateTimeFormat('sv-SE', {timeZone:'Europe/Moscow'}).format(new Date(Date.now()+offset*86400000));
    const yesterday=date(-2),today=date(-1);
    const anonymous=await (await page.request.get('/api/v1/session')).json();
    const registered=await page.request.post('/api/v1/register',{headers:{'X-CSRF-Token':anonymous.csrf_token},data:{name:'Утренний сценарий',email:`morning-${Date.now()}@example.com`,password:'Morning-test-123',timezone:'Europe/Moscow'}});
    expect(registered.status()).toBe(201);
    const created=await page.request.post('/api/v1/sleeps',{headers:{'X-CSRF-Token':(await registered.json()).csrf_token},data:{day:yesterday,kind:'night',start:`${yesterday}T21:30:00+03:00`,end:null}});
    expect(created.status()).toBe(201);
    await page.goto(`/?date=${yesterday}`);
    await page.getByRole('button',{name:'Завершить ночной сон',exact:true}).click();
    await page.getByLabel('Конец сна (пусто — ещё спит)').fill(`${today}T07:07`);
    await page.getByRole('button',{name:'Сохранить',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    const night=page.locator('.time-row.night');
    await night.getByRole('button',{name:'Добавить заметку',exact:true}).click();
    await page.getByLabel('Заметка',{exact:true}).fill('Ночью одно кормление');
    await page.getByRole('button',{name:'Сохранить',exact:true}).click();
    await expect(night).toContainText('Ночью одно кормление');
    await page.goto(`/?date=${today}`);
    await expect(page.locator('.previous-night-context')).toContainText('21:30 — 07:07');
    const day=await(await page.request.get(`/api/v1/days/${today}`)).json();
    expect(day.previous_night.id).toBe((await created.json()).id);
    expect(day.timeline[0].start).toBe(`${today}T04:07:00Z`);
    expect(day.metrics.day_awake_seconds).toBeGreaterThan(0);
    expect(day.metrics.night_sleep_seconds).toBeNull();
    await page.goto(`/?date=${yesterday}`);
    await night.getByRole('button',{name:'Изменить заметку',exact:true}).click();
    await page.getByLabel('Заметка',{exact:true}).fill('Ночью два кормления');
    await page.getByRole('button',{name:'Сохранить',exact:true}).click();
    await page.reload();
    await expect(night).toContainText('Ночью два кормления');
    await night.getByRole('button',{name:'Изменить интервал',exact:true}).click();
    await expect(page.getByLabel('Конец сна (пусто — ещё спит)')).toHaveValue(`${today}T07:07`);
});
