import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { test, expect } from '@playwright/test';

const root = fileURLToPath(new URL('../..', import.meta.url));
const password = 'Prototype-check-123';

test('night view, admin read-only diary and immediate account block', async ({ page, browser }) => {
    const email=`night-${Date.now()}@example.com`,adminEmail=`admin-${Date.now()}@example.com`;
    const anon=await(await page.request.get('/api/v1/session')).json();
    const response=await page.request.post('/api/v1/register',{headers:{'X-CSRF-Token':anon.csrf_token},data:{name:'Ночной сценарий',email,password,timezone:'Europe/Moscow'}});
    expect(response.status()).toBe(201);
    const session=await response.json();
    const day=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Moscow'}).format(new Date(Date.now()-86400000));
    const sleep=await page.request.post('/api/v1/sleeps',{headers:{'X-CSRF-Token':session.csrf_token},data:{day,kind:'night',start:new Date(Date.now()-120000).toISOString(),end:null}});
    expect(sleep.status()).toBe(201);
    await page.goto(`/?date=${day}`);
    await expect(page.getByRole('heading',{name:'Малыш спит уже'})).toBeVisible();
    await expect(page.getByRole('button',{name:'Проснулся / заплакал',exact:true})).toHaveCount(0);
    await page.getByRole('button',{name:'Завершить ночной сон',exact:true}).click();
    await page.getByRole('button',{name:'Сохранить',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page.locator('.time-row.night')).toBeVisible();
    const command=JSON.parse(process.env.BABY_ADMIN_COMMAND || '["docker","compose","exec","-T","backend",".venv/bin/python","create_admin.py"]');
    execFileSync(command[0],[...command.slice(1),'--email',adminEmail,'--password-stdin'],{cwd:root,input:`${password}\n`,stdio:['pipe','pipe','pipe']});
    const adminContext=await browser.newContext({baseURL:new URL(page.url()).origin,viewport:{width:390,height:844}});
    const admin=await adminContext.newPage();
    await admin.goto('/login');
    await admin.getByLabel('Email',{exact:true}).fill(adminEmail);
    await admin.getByLabel('Пароль',{exact:true}).fill(password);
    await admin.getByRole('button',{name:'Войти',exact:true}).click();
    await expect(admin.getByRole('link',{name:'Профиль',exact:true})).toBeVisible();
    await admin.getByRole('link',{name:'Профиль',exact:true}).click();
    await admin.getByRole('button',{name:/Пользователи Просмотр/}).click();
    await admin.getByLabel('Поиск по имени или email').fill(email);
    await admin.getByRole('link',{name:'Открыть дневник',exact:true}).click();
    await admin.getByRole('button',{name:'Выбрать дату'}).click();
    await admin.getByRole('textbox',{name:'День дневника',exact:true}).fill(day);
    await expect(admin.locator('.time-row.night')).toBeVisible();
    await expect(admin.getByRole('button',{name:/Изменить интервал|Удалить|Завершить ночной сон/})).toHaveCount(0);
    await admin.getByRole('link',{name:'К пользователям',exact:true}).click();
    await admin.getByLabel('Поиск по имени или email').fill(email);
    await admin.getByRole('button',{name:'Заблокировать',exact:true}).click();
    await admin.getByLabel('Причина изменения статуса').fill('Проверка блокировки');
    await admin.getByRole('dialog').getByRole('button',{name:'Заблокировать',exact:true}).click();
    await expect(admin.getByText('Заблокирован',{exact:true})).toBeVisible();
    await page.reload();
    await expect(page.getByRole('alert')).toContainText('Доступ к аккаунту ограничен');
    await adminContext.close();
});
